[package]
name = "http-calculator-rs"
version = "0.1.0"
authors = ["Yung-Jin (Joey) Hu <yungjinhu@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
calculate = { path = "../calculate" }

[build-dependencies]
bindgen = "0.56.0"